
# backup_dir   where to store the local backups
backup_dir: /tmp/s3_mysql_backups

# s3_access_key_id      your Amazon S3 access_key_id
# s3_secret_access_key  your Amazon S3 secret_access_key
# s3_bucket             your Amazon S3 bucket for the backups
s3_access_key_id:
s3_secret_access_key:
s3_bucket:

# dump_user             the database user for mysqldump
# dump_pass             the password for the dump user
dump_user:
dump_pass:


## mail_to               where to send the backup summary email
mail_to:

# Mail credentials
mail_user:
mail_pass:
mail_from:  # OPTIONAL, defaults to mail_user
mail_domain:   # OPTIONAL, defaults to: smtp.gmail.com
mail_port: 587                  # OPTIONAL, defaults to: 587
mail_authentication: login      # OPTIONAL, defaults to: :login
mail_start_tls: true            # OPTIONAL, defaults to: true